name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  google_fonts: ^8.1.0
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fox.png
    - assets/narwhal.png
    - assets/bear.png
    - assets/happy.png  
    - assets/sad.png
    - assets/curious.png